FROM python:3.12-slim-bookworm

RUN apt-get update -y && apt-get install libglib2.0-0 libsm6 libxrender1 \
    libxtst6 libblas-dev liblapack-dev libatlas-base-dev gfortran \
    ffmpeg libxext6 git build-essential -y